### ISSUE TITLE
Kabooty 2.0 tracker

### ISSUE THREAD

**Issue by lvdlee** [mirage-software/Kabooty#63]
Initially going for feature and design parity, slowly adding more features over time.

- [ ] Create design system (design)
- [ ] Create design system (components/code) (50%)
- [ ] Migrate to SvelteKit 1.0 (25%)
- [ ] Create privacy policy
- [ ] Create cookie policy
- [ ] Create and show cookie banner
- [ ] Require users to sign in through specific page, and require them to accept the privacy policy prior to login
- [ ] Refactor /collabs page
- [ ] Refactor /collabs/new page
- [ ] Refactor /collabs/[id] page
- [ ] Refactor external accounts system to be extremely flexible
- [ ] Allow users to submit changes to the characters table
- [ ] Implement multi-guild support
- [ ] Allow users to add the Kabooty bot to their guild
- [ ] Create a guild management dashboard
- [ ] Refactor collab creation to be extremely flexible, and allow a set amount of pre-uploaded picks
- [ ] Rework the bump system to allow flexible settings
- [ ] Redesign the collab delivery process
- [ ] Make the collab banner delivery flexible

**Comment by Tunnelbliick** [comment]
@lvdlee just gonna add one thing the overlay for img cropping should be adjust for small laptop devices with a screen with of around 1366x768 on those devices the component becomes very small. Since it doesnt trigger the mobile view.

**Comment by htc480** [comment]
Suggestion and ideas:
-Prestige role management (only count how many collabs in a row x user has participated to determine it)
-Not sure if you'd like to work on this, I'll understand if not, but in case you do, having a management panel for supporters where I can edit their perk status, and having the role demotion automated would be good)
-Manage using and adding predefined pools, with a big image like the one used in the 5th megacollab for sign up, where an user can zoom in and look for available characters or a normal list with a lot of filter options (maybe a random dice to pick a random character too). 
-Based on user's discord roles, allow them to upload more images for different and special materials (premium users).
-More compact participant list.
-Create server economy implementation with miira bot that gives credits to the user for entering the collab, and for inviting users with a referral code.
-Punishments for users who fail to use the material based on n manual checks, maybe add an admin panel to see the user's current avatar and the avatar we made for them. (Like I do on spreadsheets currently)
-For global banners v2, let the website automate the creation of them where they show info like the current megacollab cards (ranks, level, name, gamemode, badges, etc.) Maybe make it possible to create sections on it, for staff, premium users, x category of the collab, etc
-For pre uploaded pics, the images given will be all pre cropped beforehand by me for all the assets, so users wont need to touch anything regarding the image. However they can submit another image to edit the current one, but would need to be subject to inspection by me, maybe with a kabooty or miira implementation on discord or on the admin pannel, as images need to follow a certain list of requirements to be used (an ai could also do this but too much work kek).
